### ISSUE TITLE
Group integration

### ISSUE THREAD

**Issue by AaronGilMartinez** [CollaboraOnline/collabora-drupal#52]
Some sites may use the Group module.

https://www.drupal.org/project/group

The module requires special handling for access to Collabora documents associated with content attached to a group.

**Comment by ribel** [comment]
Hi @AaronGilMartinez and @brummbar,

I [see](https://github.com/donquixote/collabora-drupal/commit/b9534c78c6051aa7b64dc2d09a55fac01b0a87de) you added dependency to the module [groupmedia](https://www.drupal.org/project/groupmedia) 4.x (which depends on Group 3.x).

It might be an issue for Open Social distribution since there we still use Group 2.x (and groupmedia 3.x).

Could you please clarify what is the purpose and the end goal of this submodule?
Would it be possible to add support of Group 2.x or move it to separate module to avoid conflicts with the composer?

Thank you!

**Comment by AaronGilMartinez** [comment]
Fixed in #64
